version: '3'

services:
  database:
    build:
      context: .
      dockerfile: sql/Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${LITSCAN_USER} -d ${LITSCAN_DB}'"]
      interval: 5s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - LITSCAN_USER=${LITSCAN_USER}
      - LITSCAN_PASSWORD=${LITSCAN_PASSWORD}
      - LITSCAN_DB=${LITSCAN_DB}
    restart: unless-stopped

volumes:
  postgres_data:
