version: '3'

services:
  explorer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python search_demo.py
    restart: always
    ports:
      - 7860:7860
